-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "heightCm" DOUBLE PRECISION,
ADD COLUMN     "lengthCm" DOUBLE PRECISION,
ADD COLUMN     "weightKg" DOUBLE PRECISION,
ADD COLUMN     "widthCm" DOUBLE PRECISION;
